config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # get "products", to: "products#index"
  # get "products/new", to: "products#new", as: "new_products"

  # get "products/:id", to: "products#show", as: :product
  # get "products/:id/edit", to: "products#edit", as: :edit_product

  # patch "products/:id", to: "products#update"
  # post "products", to: "products#create"

  resources :products do
    get "search", on: :collection #products/search -> products#search
     resources :comments, only: [ :create ] do 
        resources :votes, only: [ :create ]
     end
     resources :votes, only: [ :create ]
  end
  root "main#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :product_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product

  has_many :votes, as: :votable
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  description :string
#  name        :string
#  slug        :string
#  visible     :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_products_on_slug  (slug) UNIQUE
#
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: { message: "Name is required" }
  validates :description, presence: { message: "Description is required" }

  validates :name, length: { minimum: 5, maximum: 200 }

  has_one_attached :image, :dependent => :destroy

  # uniqueness
  # length
  # presence
  # format - Regex

  has_many :product_categories, :dependent => :destroy
  has_many :categories, through: :product_categories
  has_many :comments, -> { order("id DESC") }, :dependent => :destroy
  has_many :votes, as: :votable, :dependent => :destroy

  accepts_nested_attributes_for :categories

  scope :visible, -> { where(visible: true) }

  def category_default
    return self.categories.first.name if self.categories.any?
    "None category"
  end

  def self.populars
    joins("LEFT JOIN votes ON votes.votable_id = products.id AND votes.votable_type = 'Product'")
    .select("products.*, count(votes.id) as total")
    .group("products.id")
    .order("total DESC")
  end
end

app/models/product_category.rb
# == Schema Information
#
# Table name: product_categories
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer          not null
#  product_id  :integer          not null
#
# Indexes
#
#  index_product_categories_on_category_id  (category_id)
#  index_product_categories_on_product_id   (product_id)
#
# Foreign Keys
#
#  category_id  (category_id => categories.id)
#  product_id   (product_id => products.id)
#
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name ])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_product, only: [ :create ]

  def create
    @product.comments.create(comment_params)
    redirect_to @product, notice: "Comment was saved success"
  end

  private

  def set_product
    @product = Product.find_by slug: params[:product_id]
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # layout "custom"
  def welcome
    redirect_to products_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy ]
  def index
    current_page = params[:page] || 1
    @products = Product.populars.visible.paginate(page: current_page, per_page: 6)
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: "The product was updated"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    if @product.persisted?
      redirect_to product_path(@product), notice: "Products was created success."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, status: :see_other, notice: "The product was deleted success"
  end

  def search
    @q = params[:q]
    @products = Product.where("name LIKE ?", "%#{ @q }%").where(visible: true)
  end

  private

  def set_product
    # Before without gem friendly
    # @product = Product.find(params[:id])

    # After with gem friendly
    @product = Product.friendly.find(params[:id])
  end

  # Strong params
  def product_params
    params.require(:product).permit(:name, :description, :visible, :image, category_ids: [])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_product, only: [ :create ]
  before_action :set_comment, only: [ :create ]

  before_action :set_votable, only: [ :create ]


  def create
    Vote.create votable: @votable
    redirect_to @product, notice: "Thanks for voted."
  end

  private

  def set_votable
    if @comment
        @votable = @comment
    else
        @votable = @product
    end
  end

  def set_comment
    @comment = Comment.find(params[:comment_id]) if params.has_key? :comment_id
  end

  def set_product
    @product = Product.find_by slug: params[:product_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def simple_description(description)
    description.truncate(100)
  end

  def date_format(date)
    meses = [ "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" ]
    mes = meses[date.strftime("%-m").to_i - 1]
    dia = date.strftime("%d")
    year = date.strftime("%Y")

    "#{ dia } del #{ mes } del #{ year }"
  end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/comments/_comment.html.erb
<div class="container">
    <div class="mx-auto">
        <div class="py-4 px-8 lg:px-4 mb-4 bg-gray-50 rounded-lg">
            <p class="text-base"><%= comment.content %></p>
            <p><%= comment.votes.count %></p>
            <%= form_with model:[ @product, comment, Vote.new ] do | form | %>
                <%= form.submit "👍", class: "cursor-pointer" %>
            <% end %>
        </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @product, Comment.new ] do | form |%>
    <div class="mt-4">
        <%= form.text_area :content, placeholder: "Your comment", class: "relative mb-2 md:mb-0 w-full py-4 pl-4 text-sm border rounded resize-none bg-gray-50" %>
    </div>
    <div class="mt-4">
        <%= form.submit "Comment", class: "cursor-pointer inline-block  py-4 px-8 leading-none text-white bg-red-600 hover:bg-red-700 font-semibold rounded shadow" %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Product Hunt" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind.min.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "partials/messages" %>
    <%= render partial: "partials/navbar" %>
    <div class="container px-4 mx-auto">
      <%= yield %>
    </div>
  </body>
  <script>
    document.addEventListener("turbo:load", function() {
      document.querySelectorAll(".message-close").forEach(button => {
        button.addEventListener("click", function() {
          let message = document.getElementById(`message-${this.value}`);
          if (message) {
            message.style.display = "none";
          }
        });
      });
    });
  </script>
</html>

app/views/layouts/custom.html.erb
<html>
    <head>
        <title>Custom layout</title>
    </head>
    <body>
        <%= yield %>
    </body>
</html>

app/views/main/welcome.html.erb
<h2>Hola <%= @name %> desde el primer template</h2>

app/views/partials/_message.html.erb
<div class="px-6 mt-2 messages" id="message-<%= index %>">
    <div class="p-6 bg-white border-l-4 border-indigo-500 shadow-md rounded-r-lg">
        <div class="flex items-center">
            <h3 class="text-indigo-800 font-medium"><%= message %></h3>
            <button class="ml-auto message-close" value="<%= index %>">
                <svg class="text-indigo-800" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6.93341 6.00008L11.1334 1.80008C11.4001 1.53341 11.4001 1.13341 11.1334 0.866748C10.8667 0.600081 10.4667 0.600081 10.2001 0.866748L6.00008 5.06675L1.80008 0.866748C1.53341 0.600081 1.13341 0.600081 0.866748 0.866748C0.600082 1.13341 0.600082 1.53341 0.866748 1.80008L5.06675 6.00008L0.866748 10.2001C0.733415 10.3334 0.666748 10.4667 0.666748 10.6667C0.666748 11.0667 0.933415 11.3334 1.33341 11.3334C1.53341 11.3334 1.66675 11.2667 1.80008 11.1334L6.00008 6.93341L10.2001 11.1334C10.3334 11.2667 10.4667 11.3334 10.6667 11.3334C10.8667 11.3334 11.0001 11.2667 11.1334 11.1334C11.4001 10.8667 11.4001 10.4667 11.1334 10.2001L6.93341 6.00008Z" fill="currentColor"></path>
                </svg>
            </button>
        </div>
    </div>
</div> 

app/views/partials/_messages.html.erb
<section>
    <% flash.each_with_index do | message, index | %>
    <%= render partial: "partials/message", locals: { message: message[1], index: index } %>
    <% end %>
</section>

app/views/partials/_navbar.html.erb
<section class="py-8 px-4 xl:px-10">
    <nav class="relative">
        <div class="flex justify-between items-center">
            <%= link_to root_path do %>
                <%= image_tag "logo.png", size: "250x250" %>
            <% end %>
            <div class="lg:hidden">
                <button class="navbar-burger flex items-center p-3 hover:bg-gray-50 rounded">
                    <svg class="block h-4 w-4" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <title>Mobile menu</title>
                        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
                    </svg>
                </button>
            </div>
            <ul class="hidden absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 lg:flex lg:w-auto lg:space-x-12">
                <%= link_to "List products", root_path, class: "text-sm font-medium" %>
                <%= link_to "New Product", new_product_path, class: "text-sm font-medium" %>
            </ul>
            <div class="hidden lg:flex">
                <%= form_tag search_products_path, method: :get do %>
                    <%= text_field_tag :q, params[:q], placeholder: "Search", class: "hidden px-4 py-3 lg:inline-block text-sm leading-normal font-medium border border-r-0 rounded-l" %>
                    <%= button_tag type: "submit" do %>
                        <svg class="text-gray-300 w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                        </svg>
                    <% end %>
                <% end %>
            </div>
        </div>
    </nav>
</section>

app/views/products/_form.html.erb
<%= form_with model: @product do | form | %>
    <% if @product.errors.any? %>
        <div class="mb-4 bg-red-200 rounded-md p-5">
            <% @product.errors.each do | error |%>
                <li><%= error.full_message %></li>
            <% end %>
        </div>
    <% end %>
    
    <div class="mb-4">
        <%= form.text_field :name, placeholder: "Name product", class: "appearance-none block w-full py-3 px-4  text-gray-700 bg-gry-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none" %>
    </div>
    <div class="mb-4">
        <%= form.text_area :description, placeholder: "Description product", class: "appearance-none block w-full py-3 px-4  text-gray-700 bg-gry-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none" %>
    </div>
    <div class="mb-4">
        <%= form.label "Publish" %>
        <%= form.check_box :visible %>
    </div>

    <div class="mb-4">
        <%= form.file_field :image %>
    </div>

    <div class="mb-4">
        <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do | category | %>
            <%= category.label class: "form-check-label text-lg inline-block text-gray-600" do %>
                <%= category.check_box + category.text %>
            <% end %>
        <% end %>
    </div>
    <div class="mb-4">
        <%= form.submit "Save Product", class: "cursor-pointer inline-block  py-4 px-8 leading-none text-white bg-red-600 hover:bg-red-700 font-semibold rounded shadow" %>
    </div>
<% end %>

app/views/products/_product.html.erb
<div class="w-full md:w-1/2 lg:w-1/3 p-3">
    <div class="p-6 border rounded-xl">
        <div class="relative h-52 mb-6">
            <span class="absolute top-0 right-0 mt-4 mr-4 text-xs text-white px-2 py-1 font-semibold bg-gray-600 bg-opacity-100 rounded-md uppercase">
                <%= product.category_default %>
            </span>
            <% if product.image.present? %>
                <%= image_tag product.image, class: "w-full h-full object-cover rounded-lg"%>
            <% end %>
        </div>
        <span class="inline-block mb-4 text-xs text-gray-500"><%= date_format( product.created_at ) %></span>
        <h2 class="mb-4 text-2xl font-semibold font-heading"><%= product.name %></h2> 
        <p class="mb-4 text-gray-500 leading-relaxed"><%= simple_description( product.description ) %></p>
        <%= link_to "Conoce más", product, class: "text-lg font-medium text-red-500 underline hover:no_underline" %>
    </div>
</div>

app/views/products/edit.html.erb
<section class="relative py-10 overflow-x-hidden">
  <div class="container">
    <h2 class="mb-6 lg:mb-10 text-4xl font-semibold font-heading">Edit product</h2>

    <div class="relative flex flex-wrap items-center -mx-4">
      <div class="relative w-full  px-4 pb-12 lg:pb-0">
            <%= render partial:'form' %>
      </div>
  </div>
</section>

app/views/products/index.html.erb
<section class="relative">
    <div class="container px-4 mx-auto">
        <div class="max-w-3x1 mb-20 mx-auto text-center">
            <h2 class="mt-8 mb-10 text-4xl font-semibold font-heading">The most popular products</h2>
        </div>
        <div class="flex flex-wrap -m-3 mb-16">
            <%= render partial: "product", collection: @products %>
        </div>
        <div class="text-center">
            <% if @products.next_page.present? %>
                <%= link_to "View more products", products_path(page: @products.next_page), class: "mb-10 px-6 py-4 text-sm text-white font-semibold bg-red-400 hover:bg-red-600 rounded-md" %>
            <% end %>
        </div>
    </div>
</section>

app/views/products/new.html.erb
<section class="relative">
    <div class="container px-4 mx-auto">
        <div class="mb-6 py-6 px-6 lg:pl-12 lg:pr-6 bg-gray-50 rounded-xl">
            <div class="flex flex-wrap -mx-4">
                <div class="w-full lg:w-2/3 px-4 mb-4 lg:mb-0">
                    <div class="max-w-xl lg:pt-6">
                        <div class="max-w-md mb-10">
                            <h2 class="text-3xl md:text-4xl font-semibold font-heading">Create new product</h2>
                        </div>
                        <%= render partial: "form" %>
                    </div>
                </div>
                <div class="w-full lg:w-1/3 px-4">
                    <div class="h-80 lg:h-40">

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/products/search.html.erb
<section class="relative">
  <div class="container px-4 mx-auto">
    <div class="max-w-3xl mb-20 mx-auto text-center">
      <h2 class="mt-8 mb-10 text-4xl font-semibold font-heading">
        Searchs results: <%= @q %>
      </h2>
    </div>
    <div class="flex flex-wrap -m-3 mb-16">
        <%= render partial:'product', collection:@products %>
  </div>
</section>

app/views/products/show.html.erb
<section class="relative py-10 overflow-x-hidden">
    <div class="container  mx-auto">
        <div class="relative flex flex-wrap items-center -mx-4">
            <div class="relative w-full lg:w-1/2 px-4 pb-12 lg:pb-0">
                <h2 class="mb-6 lg:mb-10 text-4xl font-semibold font-heading">
                    <%= @product.name %>
                </h2>
                <p class="mb-6 lg:mb-10 text-xl text-gray-500">
                    <%= @product.description %>
                </p>
                <div class="mb-10 border rounded-lg">
                    <% @product.categories.each do | category | %>
                        <p class="font-semibold font-heading"><%= category.name %></p>
                    <% end %>
                </div>
                <%= link_to "Edit", edit_product_path(@product), class:"cursor-pointer inline-block  py-4 px-8 leading-none text-white bg-red-600 hover:bg-red-700 font-semibold rounded shadow" %>
                <%= link_to "Delete", 
                    product_path(@product), 
                    data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the product?" }, 
                    class:"cursor-pointer inline-block  py-4 px-8 leading-none text-red underline hover:no-underline font-semibold" 
                %>
            </div>
            <div class="w-full lg:w-1/2 px-4">
                <% if @product.image.present? %>
                    <%= image_tag @product.image, class: "w-full h-112 mx-auto mb-6 md:mb-0 rounded-xl object-cover" %>
                <% end %>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="mb-4">
        <%= form_with model: [ @product, Vote.new ] do | form | %>
            <%= form.submit "Voted 👍", class:"cursor-pointer block lg:inline-block px-5 py-3 text-sm text-center font-semibold text-red-500 hover:text-white hover:bg-red-500 border border-red-500 hover:border-red-600 rounded transition duration-200" %>
        <% end %>
    </div>
    <small>Votes: <%= @product.votes.count %></small>
</section>

<section>
    <div class="mb-4 mt-4">
        <%= render partial: "comments/form" %>
    </div>
</section>


<section>
    <div class="mb-4 mt-4">
        <%= render partial: "comments/comment", collection: @product.comments, as: :comment %>
    </div>
</section>